const DATE_MOMENT = "DD/MM/YYYY" // 05/11/2024

const DATE_TIME_MOMENT = "DD/MM/YYYY HH:mm:ss"

const TIME_MOMENT = "HH:mm"

const DATE_NAME_MOMENT = "MMMM Do, YYYY"

const DATE_NAME_TIME_MOMENT = "DD MMMM YYYY, HH:mm"

const DATE_INCOMING_FORMAT_MOMENT = "M/D/YYYY h:mm:ss A Z"



const APP_FORMATS = {
  DATE_MOMENT,
  DATE_TIME_MOMENT,
  TIME_MOMENT,
  DATE_NAME_MOMENT,
  DATE_NAME_TIME_MOMENT,
  DATE_INCOMING_FORMAT_MOMENT
}

export default APP_FORMATS
