const DATE_MOMENT = "DD/MM/YYYY" // 05/11/2024

const DATE_MOMENT_TIME = "DD/MM/YYYY HH:mm:ss"

const TIME_MOMENT = "HH:mm"

const DATE_MOMENT_NAME = "MMMM Do, YYYY"

const DATE_MOMENT_MONTH_NAME = "MMM Do, YYYY"


const DATE_MOMENT_NAME_TIME = "DD MMMM YYYY, HH:mm"

const DATE_MOMENT_INCOMING = "YYYY-MM-DD HH:mm:ss.SSSSSSS Z"



const APP_FORMATS = {
  DATE_MOMENT,
  DATE_MOMENT_TIME,
  TIME_MOMENT,
  DATE_MOMENT_NAME,
  DATE_MOMENT_NAME_TIME,
  DATE_MOMENT_INCOMING,
  DATE_MOMENT_MONTH_NAME
}

export default APP_FORMATS
